/**
 * DOB Complaint Category Decoder
 * Source: NYC DOB Official Complaint Category List (Rev. 09/21)
 * https://www.nyc.gov/assets/buildings/pdf/complaint_category.pdf
 *
 * Codes sourced from NYC Open Data dataset eabe-havv (DOB Complaints Received).
 */

const COMPLAINT_CATEGORIES: Record<string, string> = {
  // ── Numeric codes (01–99) ──
  "01": "Accident — Construction/Plumbing",
  "02": "Accident — To Public",
  "03": "Adjacent Buildings — Not Protected",
  "04": "After Hours Work — Illegal",
  "05": "Permit — None (Building/PA/Demo etc.)",
  "06": "Construction — Change Grade/Watercourse",
  "07": "Construction — Change Watercourse",
  "08": "Contractor's Sign — None",
  "09": "Debris — Excessive",
  "10": "Debris/Building — Falling or In Danger of Falling",
  "11": "Demolition — No Permit",
  "12": "Demolition — Unsafe/Illegal/Mechanical",
  "13": "Elevator In FDNY Readiness — None",
  "14": "Excavation — Undermining Adjacent Building",
  "15": "Fence — None/Inadequate/Illegal",
  "16": "Inadequate Support/Shoring",
  "17": "Material/Personnel Hoist — No Permit",
  "18": "Material Storage — Unsafe",
  "19": "Mechanical Demolition — Illegal",
  "20": "Landmark Building — Illegal Work",
  "21": "Safety Net/Guard Rail — Damaged/Inadequate/None (Over 6 Stories)",
  "22": "Safety Netting — None",
  "23": "Sidewalk Shed/Supported Scaffold — Inadequate/Defect/None/No Permit",
  "24": "Sidewalk Shed — None",
  "25": "Warning Signs/Lights — None",
  "26": "Watchman — None",
  "27": "Auto Repair — Illegal",
  "28": "Building — In Danger of Collapse",
  "29": "Building — Vacant, Open and Unguarded",
  "30": "Building Shaking/Vibrating/Structural Stability Affected",
  "31": "Certificate of Occupancy — None/Illegal/Contrary to CO",
  "32": "C of O — Not Being Complied With",
  "33": "Commercial Use — Illegal",
  "34": "Compactor Room/Refuse Chute — Illegal",
  "35": "Curb Cut/Driveway/Carport — Illegal",
  "36": "Driveway/Carport — Illegal",
  "37": "Egress — Locked/Blocked/Improper/No Secondary Means",
  "38": "Egress — Exit Door Not Proper",
  "39": "Egress — No Secondary Means",
  "40": "Falling — Part of Building",
  "41": "Falling — Part of Building in Danger Of",
  "42": "Fence — Illegal",
  "43": "Structural Stability Affected",
  "44": "Fireplace/Wood Stove — Illegal",
  "45": "Illegal Conversion",
  "46": "PA Permit — None",
  "47": "PA Permit — Not Being Complied With",
  "48": "Residential Use — Illegal",
  "49": "Storefront/Business Sign/Awning/Marquee/Canopy — Illegal",
  "50": "Sign Falling/Danger/Sign Erection — Illegal",
  "51": "Illegal Social Club",
  "52": "Sprinkler System — Inadequate",
  "53": "Vent/Exhaust — Illegal/Improper",
  "54": "Wall/Retaining Wall — Bulging/Cracked",
  "55": "Zoning — Non-Conforming",
  "56": "Boiler — Fumes/Smoke/Carbon Monoxide",
  "57": "Boiler — Illegal",
  "58": "Boiler — Defective/Inoperative/No Permit",
  "59": "Electrical Wiring — Defective/Exposed/In Progress",
  "60": "Electrical Work — Improper",
  "61": "Electrical Work — Unlicensed/In Progress",
  "62": "Elevator — Danger Condition/Shaft Open/Unguarded",
  "63": "Elevator — Defective/Inoperative",
  "64": "Elevator Shaft — Open and Unguarded",
  "65": "Gas Hook-Up/Piping — Illegal or Defective",
  "66": "Plumbing Work — Illegal/No Permit (Sprinkler/Standpipe)",
  "67": "Crane — No Permit/License/Cert/Unsafe/Illegal",
  "68": "Crane/Scaffold — Unsafe/Illegal Operations",
  "69": "Crane/Scaffold — Unsafe Installation/Equipment",
  "70": "Suspension Scaffold Hanging — No Work In Progress",
  "71": "SRO — Illegal Work/No Permit/Change in Occupancy",
  "72": "SRO — Change in Occupancy/Use",
  "73": "Failure to Maintain",
  "74": "Illegal Commercial/Manufacturing Use in Residential Zone",
  "75": "Adult Establishment",
  "76": "Unlicensed/Illegal/Improper Plumbing Work In Progress",
  "77": "Contrary to LL58/87 (Handicap Access)",
  "78": "Privately Owned Public Space — Non-Compliance",
  "79": "Lights from Parking Lot Shining on Building",
  "80": "Elevator — Not Inspected/Illegal/No Permit",
  "81": "Elevator — Accident",
  "82": "Boiler — Accident/Explosion",
  "83": "Construction — Contrary/Beyond Approved Plans/Permits",
  "84": "Façade — Defective/Cracking",
  "85": "Failure to Retain Water/Improper Drainage (LL103/89)",
  "86": "Work Contrary to Stop Work Order",
  "87": "Request for Deck Safety Inspection",
  "88": "Safety Net/Guard Rail — Damaged/Inadequate/None (6 Stories or Less)",
  "89": "Accident — Cranes/Derricks/Suspension",
  "90": "Unlicensed/Illegal Activity",
  "91": "Site Conditions Endangering Workers",
  "92": "Illegal Conversion of Manufacturing/Industrial Space",
  "93": "Request for Retaining Wall Safety Inspection",
  "94": "Plumbing — Defective/Leaking/Not Maintained",
  "95": "Bronx 2nd Offense Pilot Project",
  "96": "Unlicensed Boiler/Electrical/Plumbing/Sign Work Completed",
  "97": "Other Agency Jurisdiction",
  "98": "Other — Miscellaneous",
  "99": "Other — General Complaint",

  // ── Alphanumeric codes (1A–8P) ──
  "1A": "Illegal Conversion — Commercial to Dwelling Units",
  "1B": "Illegal Tree Removal/Topo Change in SNAD",
  "1C": "Damage Assessment Request or Report (Disaster)",
  "1D": "Con Edison Referral",
  "1E": "Suspended Scaffolds — No Permit/License/Dangerous/Accident",
  "1F": "Failure to Comply with Annual Crane Inspection",
  "1G": "Stalled Construction Site",
  "1H": "Emergency Asbestos Response Inspection",
  "1J": "Jewelry/Dentistry Torch — Gas Piping Removed w/o Permit",
  "1K": "Bowstring Truss Tracking Complaint",
  "1L": "Gas Utility Referral",
  "1N": "Gas Piping — Utility Referral Follow-Up",
  "1U": "Special Operations Compliance Inspection",
  "1V": "Electrical Enforcement Work Order (DOB)",
  "1W": "Plumbing Enforcement Work Order (DOB)",
  "1X": "Construction Enforcement Work Order (DOB)",
  "1Y": "Enforcement Work Order (DOB)",
  "1Z": "Enforcement Work Order (DOB)",
  "2A": "Posted Notice or Order Removed/Tampered With",
  "2B": "Failure to Comply with Vacate Order",
  "2C": "Smoking Ban — Smoking on Construction Site",
  "2D": "Smoking Signs — No Smoking Signs Not Observed on Site",
  "2E": "Tracking Complaint for Full Demolition Notification",
  "2F": "Building Under Structural Monitoring",
  "2G": "Advertising Sign/Billboard/Posters/Flexible Fabric — Illegal",
  "2H": "Second Avenue Subway Construction",
  "2J": "SANDY — Building Destroyed",
  "2K": "Structurally Compromised Building (LL33/08)",
  "2L": "Façade (LL11/98) — Unsafe Notification",
  "2M": "Monopole Tracking Complaint",
  "2N": "COVID-19 Executive Order",
  "2P": "Façades Unit Compliance Inspection",
  "2Y": "Building Monitoring — Ongoing",
  "3A": "Unlicensed/Illegal/Improper Electrical Work In Progress",
  "3B": "Routine Inspection",
  "3C": "Plan Compliance Inspection",
  "3D": "Bicycle Access Waiver Request — Elevator Safety",
  "3E": "Bicycle Access Waiver Request — Alternate Parking",
  "3G": "Restroom Non-Compliance with Local Law 79/16",
  "3H": "DCP/BSA Compliance Inspection",
  "4A": "Illegal Hotel Rooms in Residential Buildings",
  "4B": "SEP — Professional Certification Compliance Audit",
  "4C": "Illegal Conversion — Follow-Up Inspection",
  "4D": "Construction Safety Compliance — Tracking",
  "4E": "Stalled Sites Tracking Complaint",
  "4F": "Building Compliance — Periodic Inspection",
  "4G": "Illegal Conversion No Access Follow-Up",
  "4H": "V.E.S.T. Program (DOB & NYPD)",
  "4J": "M.A.R.C.H. Program (Interagency)",
  "4K": "CSC — DM Tracking Complaint",
  "4L": "CSC — High-Rise Tracking Complaint",
  "4M": "CSC — Low-Rise Tracking Complaint",
  "4N": "Retaining Wall Tracking Complaint",
  "4P": "Legal/Padlock Tracking Complaint",
  "4Q": "Construction Safety — Special Inspection",
  "4S": "Sustainability Enforcement Work Order",
  "4W": "Woodside Settlement Project",
  "4X": "After Hours Work — With an AHV Permit",
  "5A": "Request for Joint FDNY/DOB Inspection",
  "5B": "Non-Compliance — Lightweight Materials",
  "5C": "Structural Stability Impacted — New Building Under Construction",
  "5D": "Non-Compliance — TPPN 1/00 Vertical Enlargements",
  "5E": "Amusement Ride Accident/Incident",
  "5F": "Compliance Inspection",
  "5G": "Unlicensed/Illegal/Improper Work In Progress",
  "5H": "Illegal Activity",
  "5J": "Multi Agency Joint Inspection",
  "6A": "Vesting Inspection",
  "6B": "Semi-Annual Homeless Shelter Inspection — Plumbing",
  "6C": "Semi-Annual Homeless Shelter Inspection — Construction",
  "6D": "Semi-Annual Homeless Shelter Inspection — Electrical",
  "6M": "Elevator — Multiple Devices on Property",
  "6S": "Elevator — Single Device/No Alternate Service",
  "6V": "Tenant Safety Inspection",
  "6W": "Tenant Safety — Failure to Post/Distribute",
  "6X": "Work Without Permits Watch List Compliance",
  "6Y": "Local Law Audits",
  "6Z": "Training Compliance",
  "7A": "Integrity Complaint Referral",
  "7B": "Illegal Commercial/Manufacturing Use in C1/C2 Zone",
  "7F": "CSE — Tracking Compliance",
  "7G": "CSE — Sweep",
  "7J": "Work Without a Permit — Occupied Multiple Dwelling",
  "7K": "Local Law 188/17 Compliance Inspections — Active Jobs",
  "7L": "DOHMH Referral — Tenant Protection Non-Compliance",
  "7N": "Privately Owned Public Space — Compliance Inspection",
  "7P": "Quality of Life — Noise/Dust/Vibration",
  "7Q": "Façade — Emergency Inspection Request",
  "7R": "Gas Work — Compliance Inspection",
  "7S": "Construction Site — Environmental Compliance",
  "8A": "Construction Safety Compliance (CSC) Action",
  "8P": "Proactive Enforcement — Building Inspection",
};

export function decodeComplaintCategory(code: string | null | undefined): string {
  if (!code) return "—";
  const trimmed = code.trim();
  return COMPLAINT_CATEGORIES[trimmed] || `Category ${trimmed}`;
}
