import * as React from 'npm:react@18.3.1'
import {
  Body, Container, Head, Heading, Html, Preview, Text, Section, Hr,
} from 'npm:@react-email/components@0.0.22'
import type { TemplateEntry } from './registry.ts'

const SITE_NAME = "BinCheckNYC"
const GLE_RECIPIENT = Deno.env.get('GLE_NOTIFICATION_EMAIL') || 'info@greenlightexpediting.com'

interface GleLeadNotificationProps {
  requestType?: string
  propertyAddress?: string
  clientName?: string
  clientEmail?: string
  clientPhone?: string
  items?: string[]
  urgency?: string
  priceQuoted?: number
  requestDescription?: string
}

const GleLeadNotificationEmail = ({
  requestType = 'Architect Opinion Letter',
  propertyAddress = '123 Main St, New York, NY',
  clientName = 'John Doe',
  clientEmail = 'john@example.com',
  clientPhone,
  items = [],
  urgency = 'standard',
  priceQuoted = 750,
  requestDescription,
}: GleLeadNotificationProps) => (
  <Html lang="en" dir="ltr">
    <Head />
    <Preview>New {requestType} request for {propertyAddress}</Preview>
    <Body style={main}>
      <Container style={container}>
        <Heading style={h1}>
          New {requestType} Request
        </Heading>

        <Section style={urgencyBanner(urgency)}>
          <Text style={{ margin: '0', fontSize: '13px', fontWeight: '600' as const }}>
            {urgency === 'rush' ? '🔴 RUSH REQUEST' : '🟢 Standard Timeline'}
          </Text>
        </Section>

        <Section style={detailBox}>
          <Text style={label}>Property</Text>
          <Text style={value}>{propertyAddress}</Text>

          <Text style={label}>Client</Text>
          <Text style={value}>{clientName}</Text>

          <Text style={label}>Email</Text>
          <Text style={value}>{clientEmail}</Text>

          {clientPhone && (
            <>
              <Text style={label}>Phone</Text>
              <Text style={value}>{clientPhone}</Text>
            </>
          )}

          <Text style={label}>Quoted Price</Text>
          <Text style={value}>${priceQuoted.toLocaleString()}</Text>
        </Section>

        {items.length > 0 && (
          <Section style={detailBox}>
            <Text style={label}>
              {requestType === 'Architect Opinion Letter' ? 'Selected Violations' : 'Selected Applications'}
            </Text>
            {items.map((item, i) => (
              <Text key={i} style={{ ...value, margin: '0 0 4px' }}>• {item}</Text>
            ))}
          </Section>
        )}

        {requestDescription && (
          <Section style={detailBox}>
            <Text style={label}>Additional Notes</Text>
            <Text style={value}>{requestDescription}</Text>
          </Section>
        )}

        <Hr style={divider} />
        <Text style={{ ...text, fontWeight: '600' as const, color: '#dc2626' }}>
          ⏰ Please reply to this email or call the client within 24 hours.
        </Text>

        <Text style={footer}>
          This lead was generated by {SITE_NAME}.
        </Text>
      </Container>
    </Body>
  </Html>
)

export const template = {
  component: GleLeadNotificationEmail,
  subject: (data: Record<string, any>) =>
    `New ${data.requestType || 'Service'} Request — ${data.propertyAddress || 'Property'}`,
  to: GLE_RECIPIENT,
  displayName: 'GLE lead notification',
  previewData: {
    requestType: 'Architect Opinion Letter',
    propertyAddress: '350 Fifth Avenue, New York, NY',
    clientName: 'Jane Smith',
    clientEmail: 'jane@example.com',
    clientPhone: '(212) 555-1234',
    items: ['V123456', 'V789012'],
    urgency: 'rush',
    priceQuoted: 1250,
  },
} satisfies TemplateEntry

const main = { backgroundColor: '#ffffff', fontFamily: "'Inter', Arial, sans-serif" }
const container = { padding: '24px 28px', maxWidth: '580px', margin: '0 auto' }
const h1 = { fontSize: '22px', fontWeight: '700' as const, color: '#1a1a2e', margin: '0 0 16px' }
const text = { fontSize: '14px', color: '#4a4a5a', lineHeight: '1.6', margin: '0 0 16px' }
const detailBox = { backgroundColor: '#f8f8fa', borderRadius: '8px', padding: '16px 20px', margin: '12px 0' }
const label = { fontSize: '11px', color: '#888', textTransform: 'uppercase' as const, letterSpacing: '0.5px', margin: '0 0 2px', fontWeight: '600' as const }
const value = { fontSize: '14px', color: '#1a1a2e', margin: '0 0 12px', fontWeight: '500' as const }
const divider = { borderColor: '#e8e8ed', margin: '24px 0' }
const footer = { fontSize: '12px', color: '#999', margin: '16px 0 0' }

const urgencyBanner = (urgency: string) => ({
  backgroundColor: urgency === 'rush' ? '#fef2f2' : '#f0fdf4',
  borderRadius: '6px',
  padding: '10px 16px',
  margin: '0 0 16px',
  borderLeft: `4px solid ${urgency === 'rush' ? '#dc2626' : '#16a34a'}`,
})
